
import './globals.css'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
    <script src="https://kit.fontawesome.com/531ffc57b3.js" crossorigin="anonymous"></script>
    </head>
      <body>{children}</body>
    </html>
  )
}
